name: Build and test
on:
  push

jobs:
  build:
    permissions:
      contents: "write"
      id-token: "write"
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup gradle dependency cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        run: |
          ./gradlew test
      - name: Build
        run: |
          ./gradlew clean build -x test
